

SELECT COUNT(*) FROM ia.T_IA_ALL_CNT;
SELECT COUNT(*) FROM ia.T_IA_SUBS_SEARCHWORDS_D;
SELECT COUNT(*) FROM ia.T_IA_APP_TYPE_CNT_VOL_D;
SELECT COUNT(*) FROM ia.T_IA_APP_GROUP_CNT_VOL_D;
SELECT COUNT(*) FROM ia.T_IA_SUBS_DOMAIN_D;
SELECT COUNT(*) FROM ia.T_IA_SUBS_WEBPAGE_CAT_D;
SELECT COUNT(*) FROM ia.T_IA_CFG_CAT_TREE;
SELECT COUNT(*) FROM CKM.OFR_SUBS_HIS_D;

DESC ia.T_IA_ALL_CNT;
DESC ia.T_IA_SUBS_SEARCHWORDS_D;
DESC ia.T_IA_APP_TYPE_CNT_VOL_D;
DESC ia.T_IA_APP_GROUP_CNT_VOL_D;
DESC ia.T_IA_SUBS_DOMAIN_D;
DESC ia.T_IA_SUBS_WEBPAGE_CAT_D;
DESC ia.T_IA_CFG_CAT_TREE;
DESC CKM.OFR_SUBS_HIS_D;

SELECT * FROM ia.T_IA_ALL_CNT WHERE rownum <= 10;
SELECT * FROM ia.T_IA_SUBS_SEARCHWORDS_D WHERE rownum <= 10;
SELECT * FROM ia.T_IA_APP_TYPE_CNT_VOL_D WHERE rownum <= 10;
SELECT * FROM ia.T_IA_APP_GROUP_CNT_VOL_D WHERE rownum <= 10;
SELECT * FROM ia.T_IA_SUBS_DOMAIN_D WHERE rownum <= 10;
SELECT * FROM ia.T_IA_SUBS_WEBPAGE_CAT_D WHERE rownum <= 10;
SELECT * FROM ia.T_IA_CFG_CAT_TREE WHERE rownum <= 10;
SELECT * FROM ckm.OFR_SUBS_HIS_D WHERE data_date=(SELECT last_data_date FROM common.T_COM_META_TABLE WHERE table_name ='OFR_SUBS_HIS_D')  AND rownum <= 10;



SELECT '"' || subs_id || '"|"' || serv_no  || '"' FROM ckm.ofr_subs_his_d WHERE data_date=(SELECT last_data_date FROM common.T_COM_META_TABLE WHERE table_name ='OFR_SUBS_HIS_D')  AND rownum <= 10;  
SELECT '"' || CAT_ID || '"|"' || CAT_CD || '"|"' || CAT_FULL_CD || '"|"' || PRT_CAT_ID || '"|"' || BYS_NAME || '"|"' || DETL_FLAG || '"|"' || SYS_FLAG || '"|"' || IMG_PATH || '"|"' || CAT_DESC || '"' FROM ia.T_IA_CFG_CAT_TREE where rownum <= 10;